# Nestor Tamares (masc2010) & Alvin Somvilay (masc2006)
# CS 570, Summer 2016
# Guy Leonard
# Assignment #2
# Makefile

# Makefile for assignment #2


OBJS 	= a2.o      clock.o      opt.o      second_chance.o

pager: $(OBJS)
	g++ $(OBJS) -o pager

clean: 
	rm  -f $(OBJS)
