# Nestor Tamares (masc2006) & Alvin Somvilay (masc2006)
# CS 570, Summer 2016
# Guy Leonard
# Assignment # 1, Multithreading
# Makefile
# Creates executable named "sem"

all:	a1.cpp
	g++ -Wall -lpthread -lrt -o sem a1.cpp

